### ISSUE TITLE
save rhs from generate_ode_function

### ISSUE THREAD

**Issue by dslemusp** [pydy/pydy#365] opened 2017-02-13 17:47 UTC
Hi

First I must thank you for the effort you have put on putting together this library. I am starting using it myself because I want to move away from Matlab. 

Going to the point, I have been using the generate_ode_function to generate the rhs function which I solve using ode. So far so good. What I am trying to do now is try to save this rhs function so I don't have to generate it every time I open my notebook (Im using Jupyter Notebook btw). My model is pretty big and it takes about a minute to generate (Mostly because of the simplifications). So far I have tried to use dill and pickle with `dill.settings['recurse'] = True`, but no luck.

Maybe the answer is quite straightforward but I haven't find it. 

Thank you

**Comment by moorepants** [comment] 2017-02-13 22:53
Glad you are finding the software useful. This is something we've wanted for a while, see: https://github.com/pydy/pydy/issues/55. There are some leads there. We need to build in caching of the compiled object files. It might not be that hard to do but someone needs to spend some time on it.

**Comment by moorepants** [comment] 2017-05-30 12:22
Closing. This is a duplicate of #55.

**Closed by moorepants** 2017-05-30 12:22 UTC
Labels: codegen, enhancement
