### ISSUE TITLE
Hybrid Kane-Lagrange dynamics model

### ISSUE THREAD

**Issue by Simone2021space** [pydy/pydy#497] opened 2023-11-10 10:06 UTC
Hi team, 
I need to implement a simulation in which a 4-link manipulator captures a target body and then executes a maneuver.
For the pre-capture phase (in which the bodies are separated and independent), I am using two dynamics models obtained with Kane's method. The problem is in the post-capture phase in which I need to derive the new dynamic model for the integrated manipulator-target system. 

I initially derived from scratch another model with Kane's method to replace the first 2 models at runtime, but this is not convenient.
So I am using Lagrange multipliers to model the constraint between the target and the manipulator's last link; but this is not working properly and there is a significant constraint drift during the simulation.

Is this only due to integration errors, any idea how to solve? 
Is there a generally better approach to the problem, such as a hybrid between Kane and Lagrange/Newton-Euler?

**Comment by Peter230655** [comment] 2023-11-10 11:49
What is inconvenient about switching from one model to another one during runtime?

 

I know nothing about using Lagrange’s multiplier, but in models with Kane’s method, I have seen this drift.

Are your constraints holonomic?

 

From: Simone2021space ***@***.***> 
Sent: Freitag, 10. November 2023 11:07
To: pydy/pydy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pydy/pydy] Hybrid Kane-Lagrange dynamics model (Issue #497)

 

Hi team,
I need to implement a simulation in which a 4-link manipulator captures a target body and then executes a maneuver.
For the pre-capture phase (in which the bodies are separated and independent), I am using two dynamics models obtained with Kane's method. The problem is in the post-capture phase in which I need to derive the new dynamic model for the integrated manipulator-target system.

I initially derived from scratch another model with Kane's method to replace the first 2 models at runtime, but this is not convenient.
So I am using Lagrange multipliers to model the constraint between the target and the manipulator's last link; but this is not working properly and there is a significant constraint drift during the simulation.

Is this only due to integration errors, any idea how to solve?
Is there a generally better approach to the problem, such as a hybrid between Kane and Lagrange/Newton-Euler?

**Comment by Peter230655** [comment] 2023-11-10 11:50
What is inconvenient about switching from one model to another one during runtime?

I know nothing about using Lagrange’s multiplier, but in models with Kane’s method, I have seen this drift.
Are your constraints holonomic?

**Comment by moorepants** [comment] 2023-11-10 13:09
If you have constraints, there will be drift in integration. You have to use an integration method that minimizes the drift. I have one approach here: https://moorepants.github.io/learn-multibody-dynamics/holonomic-eom.html

**Comment by moorepants** [comment] 2023-11-10 13:10
Also, PyDy does not have an features to manage drift. It is a missing feature.

**Comment by Peter230655** [comment] 2023-11-10 13:59
A while back I simulated a 3D n link closed pendulum, that is the last point of the pendulum should be a a fixed position.
To avoid drift, I installed a VERY stiff spring between the last point of the pendulum and the fixed position, with very small 'natural' length. This avoided the drift.
Also, the max. energy stored in this spring was small compared to the energy of the system, so I think, this did not disturb the system much.

**Comment by Simone2021space** [comment] 2023-11-10 14:11
Thanks all for the reply.

I'd rather avoid implement a new dynamic model with Kane's method to simulate a joint, I don't think it is an efficient approach.
I am aware that drift problem might be solved with DAE, but I never used them as I heard are much more complex than ODE to solve.
I tried to use a spring to model the constraint force and does not work in my case, it gives rise to stiff equations.

**Comment by Peter230655** [comment] 2023-11-10 14:20
With stiff systems I have had good results with method Radau in solve_ivp.

**Comment by moorepants** [comment] 2023-11-10 17:12
> I am aware that drift problem might be solved with DAE, but I never used them as I heard are much more complex than ODE to solve.

They are more complex, but if you use a canned solver you only have supply the equations in the expected form, which is no more complex than supplying the equations to `solve_ivp` in the correct form. You can also apply Baumgarte Stabilization if you use a stepping solver.

**Comment by moorepants** [comment] 2024-08-24 11:43
Closing, reopen if there is more information.

**Closed by moorepants** 2024-08-24 11:43 UTC
